// Package shim generates the on-disk doubles: one tiny POSIX sh executable
// per manifest command, each exec-ing back into the stuntshell binary with
// the manifest and journal paths baked in as absolute, shell-quoted
// arguments. A generated bin directory is therefore self-contained — no
// environment variables to export besides PATH.
package shim

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/JaydenCJ/stuntshell/internal/manifest"
	"github.com/JaydenCJ/stuntshell/internal/version"
)

// Result summarizes what Build wrote.
type Result struct {
	BinDir   string   // directory to prepend to PATH
	LogPath  string   // journal file the doubles append to
	Commands []string // generated double names, sorted
}

// Quote returns s as one single-quoted POSIX shell word; each embedded
// single quote closes the word, emits a backslash-escaped quote, and
// reopens it — safe for every byte except NUL.
func Quote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// Script renders the executable text of one double. All paths must already
// be absolute so the double works from any working directory.
func Script(binPath, manifestPath, logPath, name string) string {
	return fmt.Sprintf(`#!/usr/bin/env sh
# %s — stunt double generated by stuntshell %s; do not edit, rebuild instead.
exec %s __act --manifest %s --log %s -- %s "$@"
`, name, version.Version, Quote(binPath), Quote(manifestPath), Quote(logPath), Quote(name))
}

// Build writes one executable double per manifest command into
// <outDir>/bin and ensures the journal file exists. logPath may be empty,
// defaulting to <outDir>/invocations.jsonl. An existing journal is kept —
// rebuilding doubles must never destroy recorded evidence; use `reset` for
// that.
func Build(m *manifest.Manifest, outDir, binPath, manifestPath, logPath string) (Result, error) {
	var res Result
	outDir, err := filepath.Abs(outDir)
	if err != nil {
		return res, fmt.Errorf("shim: %w", err)
	}
	if logPath == "" {
		logPath = filepath.Join(outDir, "invocations.jsonl")
	}
	abs := map[string]*string{"stuntshell binary": &binPath, "manifest": &manifestPath, "log": &logPath}
	for what, p := range abs {
		if *p, err = filepath.Abs(*p); err != nil {
			return res, fmt.Errorf("shim: resolve %s path: %w", what, err)
		}
	}

	binDir := filepath.Join(outDir, "bin")
	if err := os.MkdirAll(binDir, 0o755); err != nil {
		return res, fmt.Errorf("shim: %w", err)
	}
	names := m.CommandNames()
	for _, name := range names {
		script := Script(binPath, manifestPath, logPath, name)
		if err := os.WriteFile(filepath.Join(binDir, name), []byte(script), 0o755); err != nil {
			return res, fmt.Errorf("shim: write %s: %w", name, err)
		}
	}

	// Touch the journal without truncating it.
	f, err := os.OpenFile(logPath, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o644)
	if err != nil {
		return res, fmt.Errorf("shim: create journal: %w", err)
	}
	if err := f.Close(); err != nil {
		return res, fmt.Errorf("shim: create journal: %w", err)
	}

	return Result{BinDir: binDir, LogPath: logPath, Commands: names}, nil
}

// ExportLine returns the sh line that puts the doubles first in PATH,
// suitable for eval: eval "$(stuntshell path --out .stunts)".
func ExportLine(binDir string) string {
	return fmt.Sprintf(`export PATH=%s:"$PATH"`, Quote(binDir))
}
